version: "3.9"

services:
  frontend:
    image: localhost:5000/frontend
    ports:
      - "80:80"
    networks:
      - frontend

  backend:
    image: localhost:5000/backend
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    networks:
      - frontend
      - backend
    depends_on:
      - database

  database:
    image: postgres:13.6
    # command:
    #   - "postgres"
    #   - "c"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
