version: "3.9"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    networks:
      - frontend

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - database

  database:
    image: postgres:13.6
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
